import Footer from "./components/Footer";
import HeadersMenu from "./components/HeadersMenu";
import { DataStoreProvider } from "./context/DataStore";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body>
        <DataStoreProvider>
        <header>
          <HeadersMenu />
        </header>
        <main>{children}</main>
          <footer>
            <Footer/>
        </footer>
        </DataStoreProvider>
      </body>
    </html>
  );
}
