export {default as logo} from "./Shark_Black_1.png"
export {default as verified} from "./verified.png"
export {default as faster} from "./Fast_Time.png"
export {default as safe} from "./safe.png"
export {default as reliable} from "./Reliable.png"
export { default as sharkLogo } from "./white_shark_2.png"
export { default as arrowDowen } from "./arrowDowen.png"
export { default as arrowUp } from "./arrowUp.png"
export { default as table } from "./table.png"
export { default as phone } from "./phone.png"
export { default as verifiedblue } from "./verifiedblue.png"
export { default as Rectangle_46 } from "./Rectangle_46.png"
export {default as Rectangle13} from "./Rectangle13.png"
export {default as Rectangle_35} from "./Rectangle_35.png"
export { default as Rectangle_34 } from "./Rectangle_34.png"
export { default as Rectangle_48 } from "./Rectangle_48.png"
export { default as Rectangle_13 } from "./Rectangle_13.png"
export { default as Rectangle_50 } from "./Rectangle_50.png"
export { default as Rectangle_29 } from "./Rectangle_29.png"
export { default as Rectangle_99 } from "./Rectangle_99.png"
export { default as Rectangle_291 } from "./Rectangle_291.png"
export { default as whathsApp } from "./whathsApp.png"
export { default as Rectangle_36 } from "./Rectangle_36.png"
export { default as Rectangle_40 } from "./Rectangle_40.png"
export { default as Rectangle114 } from "./Rectangle114.png"
export { default as Rectangle_60home } from "./Rectangle_60home.png"
export { default as Rectangle_62hom2 } from "./Rectangle_62hom2.png"
export { default as Rectangle_64home } from "./Rectangle_64home.png"
