export {default as logo} from "./Shark_Black_1.png"
export {default as verified} from "./verified.png"
export {default as faster} from "./Fast_Time.png"
export {default as safe} from "./safe.png"
export {default as reliable} from "./Reliable.png"
export { default as sharkLogo } from "./white_shark_2.png"
export { default as arrowDowen } from "./arrowDowen.png"
export { default as arrowUp } from "./arrowUp.png"
export { default as table } from "./table.png"
export { default as phone } from "./phone.png"
export { default as verifiedblue } from "./verifiedblue.png"
export { default as Rectangle_46 } from "./Rectangle_46.png"
export {default as Rectangle13} from "./Rectangle13.png"
export {default as Rectangle_35} from "./Rectangle_35.png"
export { default as Rectangle_34 } from "./Rectangle_34.png"
export { default as Rectangle_48 } from "./Rectangle_48.png"
